name: Generate OCaml documentation
on:
  pull_request:
    paths:
      - lib
  push:
    branches:
      - master
    paths:
      - lib
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: akirak
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the documentation
        run: nix develop .#odoc -c dune build @doc

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/default/_doc/_html/

  deploy:
    if: ${{ github.ref_name == 'master' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
