name: Test OCaml

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'flake.*'
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'flake.*'
      - 'README.*'
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-compiler:
          - 4
          - 5

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@41635ce4469ebffde345bae7c35663532ac1a0fc # v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
